### ISSUE TITLE
New release for Ghidra 9.2.2?

### ISSUE THREAD

**Issue by Kelebek1** [Adubbz/Ghidra-Switch-Loader#23]
You just updated Ghidra to support 9.2.2, but the latest release is back from April still. Could you put out a new release for those of us who don't want to/can't build a Java project?

**Comment by Mika-Westphal** [comment]
I know it is not a new version but you can here download the old ghidra version: https://ghidra-sre.org/releaseNotes_9.2.3.html

**Comment by DoctorGoat** [comment]
[SwitchLoader-1.4.0-11321fd-Ghidra_9.2.4.zip](https://github.com/Adubbz/Ghidra-Switch-Loader/files/6565298/SwitchLoader-1.4.0-11321fd-Ghidra_9.2.4.zip)

Here's a build. fully unofficial. Use at your own risk.

**Comment by JackWolfard** [comment]
[SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.zip](https://github.com/Adubbz/Ghidra-Switch-Loader/files/6813097/SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.zip)

Build for Ghidra 10.0. Unofficial and untested.

**Comment by MaKiPL** [comment]
[SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.2.zip](https://github.com/Adubbz/Ghidra-Switch-Loader/files/6964413/SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.2.zip)
Modified archive of https://github.com/Adubbz/Ghidra-Switch-Loader/issues/23#issuecomment-879536636 to support 10.0.2
It installs fine and recognizes the NSP files, but so far, I didn't fully test it

**Comment by CodingKoopa** [comment]
Looking at the [changelog](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.0.4_build/Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html), it looks like the API changes since 9.1.2 are pretty minimal. I don't see anything that should have affected this plugin.

With that said: [SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.4.zip](https://github.com/Adubbz/Ghidra-Switch-Loader/files/7489771/SwitchLoader-1.4.0-7ffbbf5-Ghidra_10.0.4.zip) (untested)

**Comment by ego-lay-atman-bay** [comment]
hey, uh, can someone upadate it to Ghidra 10.1.2?
